---
title: "Lab 1"
author: "Kade Spaulding"
date: "2026-08-27"
output:
  pdf_document: default
  html_document: default
---
On your Own Version
Question 1

```{r}
#a. Initialize Variables
x <- 4
y <- 6
z <- 0.57
a <- 3.7

#b. make into two by two matrix
v1 <- c(x,y)
v2 <- c(z,a)

A <- rbind(v1,v2) #row bind

#c. make vector of length 100
new_vector <- rep(c(x,y,z,a), 25)
length(new_vector)#make sure length of vector is 100
```
Question 2
```{r}
#a. generate vector with random numnbers 1 to 10 with length 10
random_vector <- sample(1:10, 10, replace = TRUE)

#b. see if each element is greater than 4
#initialize empty vector of length 10
#for i in random_vector:
  #if i > 4:
   #add "Greater than 4" to empty vector
  #else:
   #add "Not Greater than 4" to empty vector
inequality_vector <- c(rep(NA, 10))
for (i in 1:10){
  if (random_vector[i] > 4) { 
    inequality_vector[i] <- "Greater than 4"
  }
  else{
    inequality_vector[i] <- "Not Greater than 4"
  }
}
inequality_vector
#c. find proportion greater than 4
prop <- (sum(inequality_vector == "Greater than 4")/10)
prop 

#d. repeat with size 10000
random_vector <- sample(1:10, 10000, replace = TRUE)
inequality_vector <- c(rep(NA, 10000))
for (i in 1:10000){
  if (random_vector[i] > 4) { 
    inequality_vector[i] <- "Greater than 4"
  }
  else{
    inequality_vector[i] <- "Not Greater than 4"
  }
}
#c. find proportion greater than 4
prop <- (sum(inequality_vector == "Greater than 4")/10000)
prop 
```
For question 2 the proportion that is closest to the true proportion is from the vector of size 10,000. Yes this is what I expected since a larger sample size will be more representative 

Question 3
```{r}
#a. 
#matrix for seats
getSeats <- function(){
  seats <- matrix(1, nrow=3, ncol = 3)
  seats[1,1] <- 0 #driver
  seats[1,2] <- 0#doesnt exist
  return(seats)
  }
#matrix for window seats
windows <- matrix(FALSE, nrow=3, ncol=3 )
windows[, c(1,3)] <- TRUE # column 3 and 2nd 3rd seats  column one
windows[1,1] <- FALSE #driver

results_10 <- rep(NA, 10)

for (i in 1:10){
  #car matrix
  seats <- getSeats()
  
  #valid passenger seats
  possible_seats <- which(seats == 1)
  
  my_seat <- sample(possible_seats, 1)
  
  results_10[i] <- windows[my_seat]
}
results_10

sum(results_10)
```
In this simulation, I sat by a window `r sum(results_10)` out of 10 times.
```{r}
results_500 <- rep(NA, 500)
#b. Same thing with 500
for (i in 1:500){
  #car matrix
  seats <- getSeats()
  
  #valid passenger seats
  possible_seats <- which(seats == 1)
  
  my_seat <- sample(possible_seats, 1)
  
  results_500[i] <- windows[my_seat]
}


sum(results_500)
```
In this simulation, I sat by a window `r sum(results_500)` out of 500 times.